development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: depannologue_dev
  username: admin
  password: password
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: depannologue_production
  username: <%= Rails.application.secrets[:database_username] %>
  password: <%= Rails.application.secrets[:database_password] %>
  pool: 5
