# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:    3be4eb24787cc652b8991aad318291e4474cf707a22fb47ad92dfa05e65722a1aef7212abcc60f11fd2679017689c549622b90111729d36ce7dde1e108856678
  twilio_account_sid: ACad5a750df97dae8b3c5bda5aba45ac50
  twilio_auth_token:  b7febfe45ba6949f7e8dfc4c712be2c8
  twilio_from:        32460200177
  default_from:       noreply@depannologue.com
  host:               http://localhost:3000
  lockup_actived:     false
  lockup_codeword:    love
  mailgun_api_key:    key-90f2790da18c8f7a93bbf7999ec6c77f
  mailgun_domain:     sandbox2ceff1ee93d84edf9664f89fc67944b4.mailgun.org

staging:
  secret_key_base:    fb0f037ae8b954db724c08f824b4030389798c20f600d7b3dc70af2db5e6c8b48fe41d326be8858dd87ec8868aaadfc816bee6b3be6ca9d3ff2e7a407273b5f9
  twilio_account_sid: AC57e156e38e25920c20599ae15549ff0f
  twilio_auth_token:  f40f003064270f145fdffdf91bce2102
  twilio_from:        33644605079
  default_from:       noreply@depannologue.com
  lockup_actived:     true
  lockup_codeword:    love
  host:               www-staging.depannologue.fr
  mailgun_api_key:    key-90f2790da18c8f7a93bbf7999ec6c77f
  mailgun_domain:     sandbox2ceff1ee93d84edf9664f89fc67944b4.mailgun.org


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: AC57e156e38e25920c20599ae15549ff0f
  twilio_auth_token:  f40f003064270f145fdffdf91bce2102
  twilio_from:        33644605079
  default_from:       noreply@depannologue.com
  lockup_actived:     true
  lockup_codeword:    love
  host:               www.depannologue.fr
  mailgun_api_key:    key-90f2790da18c8f7a93bbf7999ec6c77f
  mailgun_domain:     mg.depannologue.fr
  database_username:  deploy
  database_password:  deploy_depan_59
